services:
  wordpress:
    container_name: wordpress
    image: anideaforbusiness/wordpress-ols-super-optimized-eg:latest
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
      - SITE_URL=${SITE_URL}
      - SITE_TITLE=${SITE_TITLE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ENABLE_MODSECURITY=${ENABLE_MODSECURITY}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING}
      - ENABLE_IP_ACCESS_CONTROL=${ENABLE_IP_ACCESS_CONTROL}
      - ALLOWED_ADMIN_IPS=${ALLOWED_ADMIN_IPS}
      - WP_ADMIN_RATE_LIMIT=${WP_ADMIN_RATE_LIMIT}
      - WP_GENERAL_RATE_LIMIT=${WP_GENERAL_RATE_LIMIT}
      - WP_MEMORY_LIMIT=${WP_MEMORY_LIMIT}
      - WP_MAX_MEMORY_LIMIT=${WP_MAX_MEMORY_LIMIT}
    volumes:
      - wordpress_data:/var/www/vhosts/localhost/html
      - php_extensions:/usr/local/lsws/lsphp${PHP_VERSION}/lib/php
      - wordpress_logs:/var/log/wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
    networks: # <-- MODIFIED
      - wordpress_network
      - coolify-proxy
    depends_on:
      - mysql
    restart: always
    labels: # <-- ADDED THIS BLOCK
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${SERVICE_FQDN_WORDPRESS}`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  mysql:
    container_name: mysql
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network # This is correct, keep it internal
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest  # <-- CHANGED: Using the official image
    environment:
      - PMA_HOST=mysql      # <-- CHANGED: Correct env var for this image
    networks:
      - wordpress_network
      - coolify-proxy
    depends_on:
      - mysql
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${SERVICE_FQDN_PHPMYADMIN}`)"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80" # <-- CHANGED: Port is 80

# Definizione dei networks
networks:
  wordpress_network:
    driver: bridge
    internal: true
  coolify: # <-- ADDED THIS
    external: true

volumes:
  wordpress_data:
  db_data:
  php_extensions:
  wordpress_logs: